# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish
on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    #     settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.16.0
      with:
        checkout-fetch-depth: 0
        java-version: 11
        java-distribution: temurin
        maven-version: 3.6.3
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Publish to the Maven Central Repository
      run: mvn --batch-mode clean deploy -DperformRelease=true
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    # - name: Set up Java for publishing to GitHub Packages
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
